### PR TITLE
Pending squash: Bug fix setMaximumScaleY should be setMaximumScaleX

### PR DESCRIPTION
**Pull request by noais**

### CODE REVIEW

**Comment by yas375** [comment]
@noais let me help you a little bit with pull requests (Re #415, #413. #412...)

Here my assumption what has happened in your case:

1. you have forked the repo
2. you have added a fix to master branch (of your repo)
3. you have submitted a pull request to the original repo
4. while your pull request was not merged yet some new commits have been added to the original repo
5. probably you've decided to pull that changes to your repository. And probably merge has happened. As a result in your master there is an extra commit and now you `master` differs from the original.
6. Pull request - is a proposal of changes from one branch to another one. Your pull request is from your `noais:master` to `danielgindi:master`. And indeed you have those noisy commits in your branch.

To avoid such problems you should aim to have your `master` equal to main repo `master` or to be behind the main repo. Don't add commits to `master` of your fork. Usually when you want to contribute something you should create a separate branch, add changes to that branch and then open pull request using that branch.

In your case here is what I would recommend to do to fix the situation.

```
git clone git@github.com:noais/ios-charts.git
cd ios-charts
git remote add main git@github.com:danielgindi/ios-charts.git
git fetch main
git checkout main/master
git checkout -b fixing-setMaximumScaleY
git cherry-pick b01fa5def44c6017e043ffd7b4a2832ea71cf9bc
git push # open a pull requst; don't add any other commits to this branch
```

Then next time you will want to contribute some code to the library you can do

```
git fetch main
git checkout main/master
git checkout -b another-improvement
...
```

---

Thanks for fixing this issue. Looking forward to see the fix merged in ;) Good luck!

P.S. Let me know if you still have troubles with this and I will create a pull request for you (you still will be author of the commit).

**Comment by liuxuan30** [comment]
Oh yeah, and there is a tool called SourceTree that can help you a lo when squashing!

**Comment by noais** [comment]
Thank you @yas375 nice help.

@liuxuan30 I used SourceTree but some how the squashing is not working well. The squash are made but here on the github all changes still. Other squashing problem I have I'm going to share to you.

**Comment by liuxuan30** [comment]
right click on the last commit from master you merged, and click rebase interactively and check squash, will it work for you?

Use `git log` to make sure all your changes are in a single commit after latest master.

**Pull request closed without merging**
