### PR TITLE
Approved, pending styling: Fix Scroll issue when the graph is in a UITableView

### PR DESCRIPTION
**Pull request by coupgar**
foundScrollView  will be UITableWrepperView Not UITableView, which will cause TableView Scroll issue

### CODE REVIEW

**Comment by danielgindi** [comment]
Nice catch!
Although this PR is mis-styled...
Please clean it up, match the code styling of the project, squash everything together and then we'll merge ;-)

**Comment by danielgindi** [comment]
Although, wouldn't we want to check for the specific case of `UITableViewWrapperView` via the class name? or does this apply to all UITableViews which are wrapped in UIScrollViews?

**Comment by coupgar** [comment]
I was worried that Apple won't be happy if we use `UITableViewWrapperView` class name to check this case. 
I will take the advice and update the pull request. :-)

**Comment by petester42** [comment]
I don't think referencing a non public class is ideal if it works with UIScrillView. Is there scrolling issues within a collection view?

**Comment by coupgar** [comment]
Actually you cannot scroll up/down when the chart view is in a `UITableView`,  Collection View has not been tested @petester42

**Comment by petester42** [comment]
In that case I would assume that it would be the same for any subclass of `UIScrollView` such as `UITableView` and `UICollectionView`. Its worth to try it out to see.

**Comment by danielgindi** [comment]
I know that inside a UIScrollView works, haven't tested UITableView.
It should be tested to make sure that this commit handles these cases
properly

**Comment by coupgar** [comment]
@petester42 This hack only happens in a `UITableView`.  `UICollectionView` does not have a WrepperView,  so it works fine with ColloctionView.

**Comment by petester42** [comment]
I just tested this and the fix works for UITableView. Without it the chart does not behave like if it was in a scrollview.

**Comment by danielgindi** [comment]
@petester42 :+1: to the use of `where` here :-)

**Comment by danielgindi** [comment]
@coupgar could you please squash everything together?

**Comment by petester42** [comment]
awesome thanks!

**Pull request merged**
