### PR TITLE
Adds test support without cocoapods

### PR DESCRIPTION
**Pull request by petester42**
Addresses #414 

Like #422 this does not use cocoapods as to not create an xcworkspace. For now this uses `XCTest` but  could be moved to `Quick` and `Nimble` if everyone likes it better.

### CODE REVIEW

**Comment by danielgindi** [comment]
Looks good!
I think we should add tests for the beziers too, and add edge cases (viewport encloses beginning/end of a large dataset, instead of being fully zoomed out)
But this is a good start!

**Comment by petester42** [comment]
For sure. I was just putting the infrastructure in place.

**Comment by danielgindi** [comment]
Can't auto-merge, I think it clashes with the tvOS project changes

**Comment by petester42** [comment]
Alright. I'll rebase and make things work.

**Comment by petester42** [comment]
That should fix it

**Comment by danielgindi** [comment]
Compiles fine and runs just fine :-)

**Comment by yas375** [comment]
@petester42 thanks! :+1: :rocket:

**Comment by danielgindi** [comment]
How do we re-generate those images?

While adding rotation support to labels, I have removed some "predefined" values that were there to adjust drawing quirks. Now we control the drawing more accurately and do not need those. But things have changed on a pixel level and all tests fail :(

**Comment by petester42** [comment]
In `setup` add `record = true`. An example can be seen [here](https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCaseDemo/FBSnapshotTestCaseDemoTests/FBSnapshotTestCaseDemoTests.m). It's in objective-c but it's the same thing.

**Comment by petester42** [comment]
Possibly all test can have it written but set to no just to make it easier to understand.

**Comment by danielgindi** [comment]
Thanks :-)

**Pull request merged**
