### PR TITLE
Minor refactor for BarLineChartViewBase

### PR DESCRIPTION
**Pull request by liuxuan30**
1. change all gestures and their handlers to internal
2. use import UIKit instead of UIKit.UIGestureRecognizer

### CODE REVIEW

**Comment by petester42** [comment]
What are the benefits of making them internal?

**Comment by liuxuan30** [comment]
then you can override it with your desired actions.

**Comment by petester42** [comment]
The reason I am asking is that those methods are functions specific to those gesture recognizers. Its not as simple as overriding the the subclass. I'd see a case for either making the just the variables internal or just the functions internal. I think both will lead to confusion when users override stuff.

**Comment by liuxuan30** [comment]
If both internals makes confusion, I would like to make the functions internal. 

But sometimes, we may want to replace the gestures to be our sub classes. I used to write a multiple tap gesture recognizer, and when I tried to replace it, I cannot. This is the reason why I make both internal.

It is not simple to override, but they are for advanced users :)

**Comment by petester42** [comment]
I think out of the two making the variables internal is better. The object defines what selector will get called. If you want to change the tap recognized then just replace whole object I your subclass and implement the selector. it also adds more flexibility like changing numberOfTaps etc.

**Comment by liuxuan30** [comment]
You seems right. I don't come up this way. PR updated.

**Pull request merged**
