### PR TITLE
Issue #280

### PR DESCRIPTION
**Pull request by noais**
To enable this feature needs to set lineBreakerEnabled on lineDataSet.

With this we can have break lines, the only thing we need to do is to jump a index.

For ex:
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:5 xIndex:1]];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:5 xIndex:2]];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:5 xIndex:4]];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:5 xIndex:5]];

I change the first line char example have some example. (This alteration need to be deleted).

I made this pull request to have yours opinion, if you like like it was I go to clean the code.

### CODE REVIEW

**Comment by liuxuan30** [comment]
Thanks for your effort! 

Some things needed to be improve:
1. the code style, especially the {} around if else
2. I just see you changed drawLinear, but drawCubic is not touched
3. drawLinearFill and drawCubicFill is not touched yet.

As a feature, I think it would be great to have them all in place (see the tough part? :-) )

**Comment by noais** [comment]
Ok, I'm going to finish all around linear (drawLinearFill and better format). 
Do you know some tool to format automatically swift code?

This week end I start to implement to drawCubic.

I have done this pull request more to see if you all agree with my approach to implement this new feature.
I'm going to reject my pull request and when I'm really finish I create a new pull request.

**Comment by liuxuan30** [comment]
I don't know the tool, I format manually since ios-charts has its own format. 
PS, the filling feature is tricky, remember to test 'pure negative values' and 'positive+negative values', these are the monsters when I tried to implement but got a lot of visual effect bugs.

**Comment by noais** [comment]
http://giphy.com/embed/XpdYVfb6BEm4w

**Comment by osolano** [comment]
@liuxuan30  @noais  I was able to make line gaps by setting the color array of the linedatachart set to the same color as the background for a missing data point.

For example, if there are 4 data points missing, and the 3rd one is 0 and we want to show a gap here, i would set the 3rd color in the color array to match the background of the grid. This make it look like there was a line break.

image

**Comment by noais** [comment]
@osolano this is a work around. For instance this solution doesn't work for me, because I have a gradient colour on background...

**Comment by osolano** [comment]
@noais yes purely workaround, just wanted to point it out in case you didn't have a solution before. Cheers!

**Comment by liuxuan30** [comment]
@osolano I would start working on line breaking feature 'again' maybe next month and try to fix the buggy filling portion while line is broke. Once it's done, I will try file a PR for this. But still, huge work to do, so no ETA

**Comment by noais** [comment]
@liuxuan30 I start already this implementation but I never had time to finishing. I don't know if you want to start from 0 or you want to see what I have made?

**Comment by liuxuan30** [comment]
I had my own too :) it's just about fix those annoying bugs while filling

**Comment by JCMcLovin** [comment]
Did this ever get merged and is the feature supported in version 4.0?

**Pull request closed without merging**
