### PR TITLE
Add the IndependentScatterChart to ios-charts

### PR DESCRIPTION
**Pull request by gjpc**
I am not sure what you meant by rebase. But the code is ready.

### CODE REVIEW

**Comment by danielgindi** [comment]
Rebase means cleaning up the history before merging those commits into the
repo. You should really read some on it, there ar emany tutorials out there
:)

**Comment by gjpc** [comment]
Ah! I had no idea you can change commits. So you would like me to:

1)  squash the three "add lines to scatter chart" into one commit.
2) squash the two "allow value to be the index" into a single commit

Anything else?  When I do the forced push will it change this PR or do I have to make another?

**Comment by danielgindi** [comment]
@gjpc The PR will update automagically to reflect your branch :) You could also squash merges etc.

**Comment by gjpc** [comment]
@danielgindi  rebaseing was very difficult because I started by modifying the existing Scatter charts. I hope this works for you now

**Comment by liuxuan30** [comment]
what is IndependentScatterChart? Can you give a screenshot?

**Comment by gjpc** [comment]
https://github.com/gjpc/ios-charts/blob/master/screenshots/Lined%20Scatter%20Plot.JPG

**Comment by liuxuan30** [comment]
@gjpc what's the point to connect the dots here? The chart seems more obscure to understand after connecting the dots.

**Comment by gjpc** [comment]
@liuxuan30  please see the discussion at: https://github.com/PhilJay/MPAndroidChart/issues/718

**Comment by danielgindi** [comment]
Man, this PR is a mess.
It contains 25 commits, many of them are merges or reverts.
I cannot marge such a PR - as it makes it very difficult to understand what happened.

You need to *clean it up*.
Which means removing redundant commits (like doing something and then reverting it... I do not need to see this in the commits) and crushing commits together.
This PR should have been about 2 or 3 commits, not 25...

**Comment by gjpc** [comment]
Ok, I'll get it down to 2

**Comment by gjpc** [comment]
@danielgindi I think this is what you wanted, thanks for all your patience, git is not cvs :)

**Comment by gjpc** [comment]
Hi @danielgindi  did I miss anything else you need to mere this?

**Comment by danielgindi** [comment]
I do not have lots of time currently but I'm going to try to merge the functionality of this as an optional functionality in the current Scatter chart...

**Comment by gjpc** [comment]
Should not be too difficult, that is how I started. I only separated it out as per our conversation on the enhancement thread.

**Comment by danielgindi** [comment]
Yes but the thing is doing it without impacting performance :-)
It's good that it is separate now - allowing me to work on a separate branch, comparing both charts while modifying the main one.
Hope to be done with it soon

**Comment by gjpc** [comment]
OK, just to smooth my ego a little, will you give me some mention?

**Comment by danielgindi** [comment]
Of course. It's the A of the ABCs of open source communities. It's going to
look as you've made the commits ;)

>

**Comment by gjpc** [comment]
Thanks, Daniel, just in case it helps you a bit, I merged the latest upstream master

**Comment by danielgindi** [comment]
Ok you can see it on the `independent-scatter` branch here:
https://github.com/danielgindi/ios-charts/commit/a7c7bb4caf7e68e1713468c3a021d0860a587ac8

But a few issues have to be solved first.
With your idea of index-independent entries, the lines are getting crazy when zooming in or panning.
This is not a logical chart and cannot be pushed to master until it is...

**Comment by gjpc** [comment]
I wish you luck.

**Comment by danielgindi** [comment]
Have you managed to fix this issue?

**Comment by gjpc** [comment]
@danielgindi There is nothing to fix. I think you are confused by the random data in the demo. I took the time to produce an enhanced demo and committed it to my branch. https://github.com/gjpc/ios-charts Because of the nature of the manufactured data, I did add a test in the Independent Scatter renderer  to not try to plot small datasets that that have inconsequential data in them. That is the only ios-charts mod I made in the push.

**Pull request closed without merging**
