### PR TITLE
Stop axis labels duplicating

### PR DESCRIPTION
**Pull request by noais**
This issue are documented in #315

### CODE REVIEW

**Comment by liuxuan30** [comment]
try squash first :)

**Comment by noais** [comment]
@liuxuan30 I only see only one commit:
"pick fb0672a Stop axis labels duplicating."

I don't have others.

**Comment by noais** [comment]
@liuxuan30 I create another pull request with any changes.

Here in github I have this log:

```
	Merge remote-tracking branch 'origin/master'	eb38549
 @noais	Bug fix setMaximumScaleY should be setMaximumScaleX	b01fa5d
 	Merge branch 'master' of https://github.com/noais/ios-charts …	f1005f0
 	Merge branch 'Daniel' into Noais …	be91689
 	Merge commit '3f88894f31683888862cf14312db74b05c1a0101' …	7f0010b
 	Merge branch 'master' into Noais …	63f5f1d
 	Merge commit 'cbe0bac08b0f7a2df43dc38e921c4609f29e3450' …	32e7d1b
 	Merge branch 'master' into Noais …	52b68db
 	Stop axis labels duplicating.
```

My log is:
```
commit 1297e7d4b3d24502441d8e249cc37f35c4a216ba
Author: David Miguel Vicente Ferreira <david.viceteferreira@gmail.com>
Date:   Wed Dec 30 11:34:26 2015 +0000

    Stop axis labels duplicating.

commit b3361b588ddf2553ea9de3ba0f0d289b5a258b55
Author: Petr Korolev <sky4winder@gmail.com>
Date:   Fri Dec 11 15:02:36 2015 +0200

    Added automatically generated change log file
```

**Comment by quoctc** [comment]
I have the same problem with x-Axis value, but I don't know why my issue does not go away:
https://screencast.com/t/qgIDx1eroZEv
This is my code:

        let xAxis = chartView.xAxis
        xAxis.labelFont = UIFont.robotoLight(size: 10) ?? .systemFont(ofSize: 10, weight: .light)
        xAxis.centerAxisLabelsEnabled = true
        xAxis.valueFormatter = IndexAxisValueFormatter()
        xAxis.granularityEnabled = true
        xAxis.granularity = 1.0 // only intervals of 1 day
        xAxis.labelTextColor = UIColor(color: Colors.colorWhite, alpha: 50)
        xAxis.labelPosition = .bottom
        xAxis.setLabelCount(count, force: true) //count is total of xLabels items

**Pull request closed without merging**
