### PR TITLE
Pending confirmation: Try to fix single dataSet with custom groupSpace issue #284

### PR DESCRIPTION
**Pull request by liuxuan30**
for issue #284 

How to test the difference:
Force groupSpace to return custom value or 0.8 like below:
```Swift
    /// The spacing is relative to a full bar width
    public var groupSpace: CGFloat
    {
        get
        {
            if (_dataSets.count <= 1)
            {
                return 0.8
            }
            return _groupSpace
        }
        set
        {
            _groupSpace = newValue
        }
    }
```

### CODE REVIEW

**Comment by danielgindi** [comment]
@PhilJay do you see any possible sideeffects to this?

**Comment by liuxuan30** [comment]
Why it forces to return 0.0 if only up to 1 dataSet. Is it allowed to return other value instead of 0.0 for this scenario?
I am not sure if it makes sense to return positive values. If not, then we can close it. I got this issue by QA testing.

**Comment by danielgindi** [comment]
@liuxuan30 I haven't had the time yet to look at the issue with grouped bars in combined charts... Did you have success with it? What's the status of this PR - does it correct it?

**Comment by liuxuan30** [comment]
@danielgindi I am occupied with some dev work recently, I will update as soon as I got some time.

**Comment by liuxuan30** [comment]
get some time to merge with master. The only problem still remains:
```
Why it forces to return 0.0 if only up to 1 dataSet. Is it allowed to return other value instead of 0.0 for this scenario?
I am not sure if it makes sense to return positive values. If not, then we can close it. I got this issue by QA testing.
```

**Comment by liuxuan30** [comment]
Today I have been thinking about this, groupSpace should be used when dataSets count > 1. Only one dataSet and setting groupSpace seems not make sense?

Besides, I found a bug that when trying to highlight the bars, the xIndex is not correct, due to the groupSpace is 0.8, not 0. Using 0.0 is correct highlighting. So I am thinking there must be some reasons to separate them. Closing this PR right now.

**Pull request closed without merging**
