### PR TITLE
Make the ChartXAxisRenderer more flexible: now possible to overwrite drawing the line or label of the ChartLimitLine

### PR DESCRIPTION
**Pull request by pajai**
Hi Daniel,

I have done a few refactorings of the ChartXAxisRenderer that allow the following:
- Now possible to extend the renderer and overwrite selectively the label or line drawing method for a ChartLimitLine (in my project I needed e.g. to draw a triangle as arrow at the top in one case or a short line at the bottom as well as change the label offset, now easily possible)
- Functionally does the same as before
- I have eased the visibility of ChartAxisRendererBase#transformer (easier syntax when extending ChartXAxisRenderer) and ChartUtils#drawText (possible to call the method from the ChartXAxisRenderer extension).

Thanks!
Cheers,
Patrick

### CODE REVIEW

**Comment by danielgindi** [comment]
@pajai this seems great! I would have automatically merged your PR, but in a few lines there are stray brackets... Please fix code styling to match the rest of the code and then I'll merge it in!

**Comment by pajai** [comment]
Sure. I’ll fix the styling as soon as I come to the office tomorrow. Cheers,

**Comment by pajai** [comment]
Hi Daniel, I did the code styling tuning (the last commit should be part of this pul request). Cheers & thanks!

**Comment by pajai** [comment]
Thx! There is also a similar pull request for the Android project. Cheers,

**Pull request merged**
