### PR TITLE
draw the hollow candlesticks in the traditional way

### PR DESCRIPTION
**Pull request by jfcasley**
i.e individual upper and lower wicks

### CODE REVIEW

**Comment by danielgindi** [comment]
1. Please show what you mean with images so we can compare
2. Changes like this will only be accepted if they are optional

**Comment by jfcasley** [comment]
screen shot 2015-10-30 at 6 06 42 am

**Comment by jfcasley** [comment]
https://en.wikipedia.org/wiki/Candlestick_chart

**Comment by jfcasley** [comment]
I also noticed that the default fill logic is backwards, but didn't bother to create a pull request for something that trivial

**Comment by danielgindi** [comment]
Since there were too many changes in the repo since this PR, I just recreated it over the latest code base - but without the need for a new View and Dataset :-)

Thanks!

**Pull request closed without merging**
