### PR TITLE
Adds CI

### PR DESCRIPTION
**Pull request by petester42**
Adds scripts to run the tests and add a travis configuration file. Adding CI should be as easy as toggling it on in travis after this is merged.

### CODE REVIEW

**Comment by yas375** [comment]
Cool! :+1:

**Comment by danielgindi** [comment]
Thanks :-)

**Comment by liuxuan30** [comment]
@petester42 I just want to run tests on my machien to see why it failed. I run 'rake test' in ios-charts repo, it reports No such module 'FBSnapshotTestCase'
In my understanding, the CI test will automatically download and install it, so does on my machine, right? Or I have to manually install those bundles before test?

**Comment by petester42** [comment]
Check the .travis.yml. You need to install it first.

**Pull request merged**
