### PR TITLE
fix radar chart negative value rendering bug if startAtZeroEnabled is false for issue #166

### PR DESCRIPTION
**Pull request by liuxuan30**
For issue #166 
we have to check if Double(yMin) / interval will be  -1<x<0, if this is the case, ceil(x) would be 0. but I think we need it to be -1.

In order to render the negative values correctly, 
```swift
 _yAxis.axisMinimum = _yAxis.entries[0];
```
is the key. 

I have been thinking about different ways to fix. But I was suddenly realized the whole reason is the axisMinimum is not changed while the entries have been modified. Add this line solved my problem, and other radar charts remain good on my side. So I think this should be the correct way to fix it.

@danielgindi you must double check here, because I am not sure if you missed to set it, or you intend not to set _yAxis.axisMinimum.

### CODE REVIEW

**Comment by danielgindi** [comment]
I still need to understand the different situations to see what you did here... Could you supply samples - before/after?

**Comment by liuxuan30** [comment]
This is mainly about issue #166. Current logic for negative values has defect, especially for radar chart. Go to #166 to see all the details and the screenshot before and after.

You can try on your side, just turn off startAtZeroEnabled, and feed a nagative value. We need to use floor instead of ceil for negative values.

For radar chart, `_yAxis.axisMinimum = _yAxis.entries[0];` is missing for correctly rendering negative values;

For commit: `fix drawing out of bound negative value axis labels issue`:
If the axis contains negative values, it will draw out of the bound; I have a screenshot in issue #166 as well.

For commit: `drawExtras should also be included before restoring clipped context`:
I think drawExtras should be included in the clipped context; otherwise it will render out of the chart.

**Comment by liuxuan30** [comment]
I will close this since this mixed up some different issue here, though it is quite slight. I will use different branch for this issue.

**Comment by liuxuan30** [comment]
OK, split done. see pull request #207, #208, #209

**Pull request closed without merging**
