### PR TITLE
Issue: #316

### PR DESCRIPTION
**Pull request by noais**
Fixes xcode beta 6 compile errors 
Issue: #316

### CODE REVIEW

**Comment by danielgindi** [comment]
This includes more commits than the actual fix

**Comment by noais** [comment]
Can you describe this issues maybe I can help?

**Comment by danielgindi** [comment]
PRs should be on separate branches. If it is on `master`, then when you add more commits to master they are added to the PR too...

**Comment by danielgindi** [comment]
Now I realize that "fix bug" is a commit to fix your previous commit. Please squash them together in order to pull them.

**Comment by danielgindi** [comment]
Anyway I'm going to let Xcode do that now and will close the issue.

**Pull request closed without merging**
