### PR TITLE
Start of work for floating point precision for the x-axis, Issue 194

### PR DESCRIPTION
**Pull request by StephanieB5**
The purpose of this pull request is to open a place for conversation about work I've started to resolve Issue #194 .  This is a work in progress.  My goal is to have the work pulled into mainline when it is ready.  On my fork I've started a Wiki page to give an idea of my current understanding of the problem and roadmap for my work. 

https://github.com/StephanieB5/ios-charts-xTime/wiki/ios-charts-xTime:-support-of-floating-point-and-date-x-axis-values

@RyGuyM, @liuxuan30 have been great to offer support and mentioned interest in a conversation.  I feel code is greatly improved by review and feedback so please let me know what you think.

Thanks!

### CODE REVIEW

**Comment by RyGuyM** [comment]
Let's get the fork up to date with the current version. I took a quick stab at Scatter Charts on my local branch yesterday and made good progress on a scaled value rendering but where things start to break down are the labels and grids.

**Comment by StephanieB5** [comment]
I've got the fork up to date.  Would you like to work together to get this feature rolled out?  I'm always open to ideas. :)

**Comment by liuxuan30** [comment]
@danielgindi since it's a big move, shall we use another branch for it?

**Comment by danielgindi** [comment]
Of course- this kind of stuff should be thoroughly tested before going into master... Feel free to create a branch

**Comment by danielgindi** [comment]
Btw, just a hint - it's possible that all you need is actually an extension for the XAxis, not a whole chart-view. Otherwise you would have to create time versions of almost all charts. 
Just try to generify it.

**Comment by StephanieB5** [comment]
Thanks @liuxuan30 and @danielgindi!  A branch would be great.  It's in a branch on my side too. :)  A generalized XAxis should hopefully take care of labelling issues.  However, I believe the changes will spread beyond that though. For example functions like BarLineChartViewBase::lowestVisibleXIndex will need to be changed.  

That being said, in the end I'm hoping that the changes end up being small enough that classes like BarLineChartViewBase can be safely changed.  I've just isolated things into separate classes for now.

**Comment by RyGuyM** [comment]
I'm doing some work on the lowestVisibleXIndex right now which doesn't work in a value scheme. In the index scheme order is based on index so we can always assume index[0] will appear before index[1] but in the value scheme index[0] might have a value of 10 and index[1] might be -5 so we need to filter or renderings based on position instead.

I agree with @danielgindi that an extension for XAxis for time values could useful. I haven't looked at times yet though, just numerical based scaling.

**Comment by StephanieB5** [comment]
If you use time as represented in seconds from a reference date, such as NSTimeInterval, then hopefully getting date representation from values should just be a matter of formatting the labels. The XAxis has space for a ValueFormatter, it just needs to be generalized to support customs formatting.

I suspect the data points will need to be ordered by xNumericVal before rendering.  For example in line chart rendering you to know which point is next to which according to their place on the x-axis.

@RyGuyM it appears that we're working in the exact same area of the code.

**Comment by liuxuan30** [comment]
I have created a branch floatXAxis from master. You can merge it there. Keep the code style :)

**Comment by StephanieB5** [comment]
Thanks!  

Sorry about the scattered commits.  On my end, I like to do fine grain commits to retrace steps in case bugs appear.  I'll squash those together to make it easier to see the changes overall.  I appreciate the feedback. :)  

Once things are squashed I'll open a new pull request (into floatXAxis this time).

**Comment by StephanieB5** [comment]
Closing this pull request in preparation for pull request into floatXAxis branch.

**Pull request closed without merging**
