### PR TITLE
Allow setting maximum y-scale factor

### PR DESCRIPTION
**Pull request by noais**

### CODE REVIEW

**Comment by liuxuan30** [comment]
Hey noais, thanks for your PR! There is a issue about maxScaleY:https://github.com/danielgindi/ios-charts/issues/256. You will see Daniel said `maxScaleY is just a much more complex issue :-)`

So I hope you could read the post, and test more. It's not as easy as you would think  first about maxScaleY :)

**Comment by noais** [comment]
I implement this because there aren't a way to stop the zoom in on the y axis, like the x axis. With this feature Is possible avoid labels duplicated. I implemented this because I have the same issue like #315

**Comment by noais** [comment]
I need to read more carefully the issue #256 because I don't get the problem.

**Comment by liuxuan30** [comment]
@noais, I remember the problem I had is for horizontal bar chart. I don't know why maxScaleY is complcated as @danielgindi said, but when I think I face the same problem, horizontal bar chart's xAxis is like yAxis, and the maxScaleX issue on horizontal bar chart is same as maxScaleY issue on bar chart I guess.

Anyway, you may want to test more on bar/line/horizontal bar chart for maxScaleY. @danielgindi, do you remember why maxScaleY is complicated?

**Comment by noais** [comment]
@liuxuan30 I found this wrong behaviour:
http://imgur.com/chYcHLV

Is this one the problem?

This can be resolved when we have the max Y we can block the all zoom in events.

**Comment by noais** [comment]
This problem happen with setMaximumScaleX and this is already in the main project.
I don't see the diference between setMaximumScaleX with setMaximumScaleY.

This behaviour must be fixed, for both cases beyond this problem I don't see what issue can have maxScaleY specifically?

**Comment by liuxuan30** [comment]
if you are confident, just test different charts as many as possible with different situations.

**Comment by danielgindi** [comment]
There were a few reasons:
1. That conversation at #256 was in the context of the plans to change x-indexes into x-values. Along with supporting logarithmic y-axis etc. We are looking at ways to implement those, and it requires mainly a rewrite of the Transformer and the ViewPortHandler. We are lucky that they are different classes and not just code mixed in random places in the project...
2. There's the possible collisions with auto-scaling and other features that work on the Y axis

But this is fine as a solution for the time being - as it seems to work in "normal" situations.

Thanks :-)

**Pull request merged**
