### PR TITLE
Stop axis labels duplicating. #315  [Pending squash and cleanup]

### PR DESCRIPTION
**Pull request by noais**
With one commit :+1:

### CODE REVIEW

**Comment by liuxuan30** [comment]
I think you need to practice "squash into 1 commit" by creating test branch and simulate the normal cases. Like you have create several commits, and merge upstream master into your test branch, and squash it into one based on the upstream master. It's too much burden if you manually copy paste the code.

If you are using SourceTree, you could right click the latest commit, Rebase, and let it rebase the code on the latest commit.
In order to squash, you need to right click the commit before your first commit, and Rebase Interactively. There you have a squash option :-)

**Comment by noais** [comment]
The problem was my master branch wasn't correctly synchronised with the origin and I thought it was.
Thanks

**Comment by liuxuan30** [comment]
you could make sure you don't touch master, just keep it sync with upstream

**Comment by petester42** [comment]
Are there any cases where you would want values to be duplicated? I get why the code duplicates values but users usually would assume to not have repeating values like a real graph.

**Comment by liuxuan30** [comment]
I guess it's just a switch to not triggering the code?

**Comment by noais** [comment]
@petester42 people was asking to create allowRepeatedValues. So I created, but I can't see one example where I want to see repeated values.

**Comment by danielgindi** [comment]
@noais thank you!
I've adjusted the terminology for the better, and made this the new default behaviour.

@petester42 a case where people will want "repeating values" is for example when you want to show grid lines - while hiding the value labels - but you want to always have at least 5 grid lines on display. No matter how fractioned the value intervals are...

**Pull request merged**
