### PR TITLE
Let framework be used from app extensions

### PR DESCRIPTION
**Pull request by adonaire-sage**
Fixes issue: https://github.com/danielgindi/ios-charts/issues/693

### CODE REVIEW

**Comment by petester42** [comment]
From what I can gather this just adds `APPLICATION_EXTENSION_API_ONLY` to the project file

**Comment by adonaire-sage** [comment]
I understand, that's fine. But do you mean rebasing just the 2 work commits or also the merges?

**Comment by petester42** [comment]
I would like it if this pull request included only the flag changes. There seems to be some logic change in the first commit. I was asking you to rebase because I wasn't sure if those came from master.

**Comment by petester42** [comment]
If the logic change is not from master and you believe it is a bug. Just make a separate pull request :+1:

**Comment by adonaire-sage** [comment]
No no, the logic change comes from master. Anyway I think the best will be create a new one with only the flag changes. Thanks!

**Comment by petester42** [comment]
Thanks. That would be great.

**Comment by danielgindi** [comment]
Just a head-up: I am planning on a release very soon. This is a small change that can be easily integrated without delaying anything, so if you want it to go in the next release please hurry :-)

**Comment by adonaire-sage** [comment]
Thanks for the heads-up @danielgindi. I'm closing this PR and opening another one with just that change.

**Pull request closed without merging**
