### PR TITLE
Try to fix wrong position bug for BarChartView + HorizontalBarChartView

### PR DESCRIPTION
**Pull request by liuxuan30**
try to fix wrong position bug for issue #214 

The idea is, because not every xIndex will have a dataEntry, if the data is invalid (nil/nan/null), the entryCount will be less than xValsCount. 

For example, xVals: [0,1,2,3,4,5,6,7,8,9,10], if there are two dataSets, like below:
xIndex:0 value:100, xIndex:10 value:200
xIndex:0 value:1000, xIndex:10 value:2000

Current logic will use entryCount instead of xValsCount to calculate the matrix and position, which will lead to shorter xPosition value on xAxis. issue #214 has the screenshot.

What I changed is I always use xValsCount and actual xIndex value to calculate.

@danielgindi There might be something I missed if I am not correct. On the other hand, if you think I am right, I would also miss places to apply the new logic, because while I am testing, I found I missed to change `getMarkerPosition`. There could be more.

I also feel it might has such issues for all bar-like charts, but I don't have time to dig out more charts. If I ran into this, I will continue trying to fix.

### CODE REVIEW

**Comment by liuxuan30** [comment]
@danielgindi as you have changed lots since 2.1.1, this PR cannot be merged with green light. I won't be able to merge newer code to this branch until I got some time to resolve the conflicts... Also need you to review the whole logic. I might miss something somewhere.

**Comment by liuxuan30** [comment]
alright, lucky night I got time to deal with the conflicts.. hope you don't mind a few more commits introduced.

**Comment by danielgindi** [comment]
Do you know how to squash commits?

**Comment by danielgindi** [comment]
If you are using SourceTree, you could right click the latest commit, Rebase, and let it rebase the code on the latest commit.
In order to squash, you need to right click the commit before your first commit, and Rebase Interativelty. There you have a squash option :-)

**Comment by liuxuan30** [comment]
actually I don't know how to squash... What's SourceTree here?

**Comment by liuxuan30** [comment]
Are you saying this?https://www.sourcetreeapp.com

I can take a look at it tomorrow. Need to handle some other stuff now.

**Comment by liuxuan30** [comment]
@danielgindi I managed to squash the commits #247 on a new branch, though it did only have one commit that includes all your commits and mine, when trying to create a PR #247, it still shows red light:  Can’t automatically merge. And showing 35 files changed.

I am no expert of git, but to keeps it simple, I think I would stay unsquashed for this PR :( at least it's clear what I have changed.

**Comment by liuxuan30** [comment]
Alright, thanks for the lesson! I managed to squash the commits.
The new PR is #248. I will close this.

**Comment by ghizoulo** [comment]
I am using v3.0.1 but still have the same problem. the bars are misplaced. Please if u can help me with that check #3154

**Pull request closed without merging**
