### PR TITLE
Fixes for beta 3

### PR DESCRIPTION
**Pull request by petester42**
This fixes some compiler errors in beta 3

### CODE REVIEW

**Comment by petester42** [comment]
hmm weird. why would it also add those past commits to the pull request.

**Comment by danielgindi** [comment]
Because it PRs the delta between the official branch and yours...

**Comment by danielgindi** [comment]
Oh it may be because today I have rebased swift-2.0 on latest changes... So the commits that your branch knows are quite different

**Comment by danielgindi** [comment]
A "hard" reset solves that problem. After that you can Cherry-pick your new commit, and `git push --force`  to get rid of the old mess

**Comment by petester42** [comment]
ya ill see if I can fix it. the errors in beta 3 are quite minimal

**Comment by danielgindi** [comment]
What did they change this time?..

**Comment by petester42** [comment]
for this project the only real change was that the init with coder became failable and the `observeValueForKeyPath` has proper types now.

**Comment by danielgindi** [comment]
Did you have a chance to check if the weird bridging helpers for ObjC can
finally be removed? I hate those...
I'm downloading beta 3 right now but it takes too long.

**Pull request closed without merging**
