### PR TITLE
Drag offset fix (again)

### PR DESCRIPTION
**Pull request by leoMehlig**
There was a bug in the previous fix. This one should now work correctly. Sorry for that.

### CODE REVIEW

**Comment by danielgindi** [comment]
Please first match it with the logic on the Android part

Also please fix the code styling...

**Comment by danielgindi** [comment]
Ok logic seems fine, but curly brackets should always be on a new line for clarity.
Also there should only be one commit in such a PR...

```
if _dataNotSet || !_dragEnabled || 
   (self.hasNoDragOffset && self.isFullyZoomedOut && !self.isHighlightPerDragEnabled)
{
  return false
}
```

**Comment by danielgindi** [comment]
The code that I've pasted here (which is actually the way you wrote it, only styled) matches the android logic, I checked. Android and iOS thinks differently about gestures, but the logics of those flags stayed the same.

**Please squash everything into one commit.**

**Comment by leoMehlig** [comment]
Shall I create a new PR with all the things I've changed in one commit?

**Comment by codeHatcher** [comment]
Is this fixed in v2.1.5 @danielgindi? I'm running into this issue all of a sudden and am trying to troubleshoot.

**Comment by danielgindi** [comment]
No its in `master`, a version release will take place soon.

> .
>

**Pull request closed without merging**
