### PR TITLE
Issues #182, #122

### PR DESCRIPTION
**Pull request by dorsoft**
#182 ChartData.removeEntryByXIndex removes the wrong entry
#122 Candle chart - make the shadow same color as an increasing/decreasing candle color

### CODE REVIEW

**Comment by danielgindi** [comment]
Hey man, thanks!
But:
1. You should separate those into two PRs (Just create two branches based on the latest commit, and cherry-pick the commits into them)
2. Please make sure code styling matches (That means `{` and `}` are on new lines, no `;` in line endings in Swift)
3. For shadow colors, we are working on a different solution, possibly more flexible, so it's still pending :-)

**Comment by liuxuan30** [comment]
Hi @danielgindi, I am also new to submit different PRs.. Any wiki for this? what you mean by `cherry-pick the commits into them`?
What I have is only a master branch in my fork, and whenever I push to my origin master, github automatically put it into the same PR, though it is for different bug...

**Comment by danielgindi** [comment]
Well as I said, commit to different branches.
You can make a PR for each branch of yours.
https://help.github.com/articles/using-pull-requests/

**Comment by liuxuan30** [comment]
Thanks. I will follow this rule next time. For my previous PR #168, sorry I have merged several fixes together. most of them are related to the same issue.

**Comment by danielgindi** [comment]
Still, you need to just create branches, from the master commit before your
changes.
Then take your new commits and move to those branches

**Comment by liuxuan30** [comment]
Maybe we could talk about it in PR #168? This PR is old, and I have been keeping it synced with the latest code. So it can be automatically merged.

**Pull request closed without merging**
