### PR TITLE
Update podspec for realm and 2.2.0

### LINKED ISSUE #723: 2.2.0 not published yet
As the title...?

```
[!] Unable to satisfy the following requirements:

- `Charts (= 2.2.0)` required by `Podfile`
```

### PR DESCRIPTION
**Pull request by petester42**
- changes podspec format to include the realm subspec
- adds cocoapods to gemfile
- updates readme to include realm pod spec

closes #723

### CODE REVIEW

**Comment by iostalk** [comment]
Is this published?

**Comment by iostalk** [comment]
[!] Unable to satisfy the following requirements:

- `Charts (= 2.2.0)` required by `Podfile`

Still not published yet

**Comment by petester42** [comment]
Publishing as we speak. Shouldn't be too much longer.

**Comment by petester42** [comment]
There seems to be issues with tagged 2.2.0 tagged version that references realm where it is not supposed to be. A 2.2.1 version will be needed since the master does not have this problem.

**Comment by petester42** [comment]
@iostalk you should be good to go now. Specify version 2.2.1 and it should be :tada:

**Comment by iostalk** [comment]
@petester42 OK, Let me have a try ! Thank you very much and happy Chinese new year!

**Comment by iostalk** [comment]
Analyzing dependencies
Fetching podspec for `React` from `./ReactComponents/node_modules/react-native`
[!] Unable to find a specification for `Charts~> 2.2.1`

Still not published yet...

**Comment by petester42** [comment]
its definitely in trunk right now. the problem seems to be that you are setting your cocoapods source to be  `./ReactComponents/node_modules/react-native` which is on your local machine. It is up to you to update that if that is how you work.

**Pull request merged**
