### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by liuxuan30** [comment]
I like the idea; but not sure what it looks like; the home page does not show many details

**Comment by korzonek** [comment]
@liuxuan30 this is very good idea and is in our backlog of things to do. Feedback is super important for us. We are small team and we launched product at the beginning of this year. Feedback helps us prioritise things in our backlog :) 

If there are any other things you would like to see in codebeat please let me know.

**Comment by danielgindi** [comment]
Actually this seems like taking the development process of track, for a number of reasons:

1. What we are creating here is a cross-platform solution, not just a framework. Stuff that makes more sense in a structural manner on the Swift side, may not be applicable or even possible on the Android side.
2. Many of the suggestions by codebeat are ones that I cannot agree with. For example:
2. 1. "too many lines in one function". The nature of rendering code is being performance-critical, while by definition you should make as little function calls as you can, and the less memory allocations the better. Adding a single function call to a loop over 1000 points in a `drawRect` code has it's impact - as ridiculous as it sounds.
2. 2. Files that seem too big. Breaking down a renderer to a few files, one with drawing the values, one with drawing the circles etc. - in my opinion will make it much harder to maintain and understand. It's not ideal to have too much code to read if you're lazy and do not want to read code, but it's also not that ideal if you can't even find the code that you need to read.

3. I know I kind of mentioned this already, but this is important: I want people to focus on developing new and important (or even nice-to-have) features, not just creating PRs that modify thousands of lines by do nothing. There are times in which we do some concentrated efforts on refactoring (like when moving between Swift versions), but in the everyday development this could make it hard to maintain, break PRs and just generally annoying...

So I'm sorry but I have to reject this one.

**Comment by grodowski** [comment]
Hi @danielgindi, another codebeat dev here. 🙂I fully agree with your concerns about codebeat's suggestions. Complexity and (especially) duplication analysis is relevant as long as your top priority is to write maintainable and understandable business code. Probably this is not your case as those factors have way lower priority when optimising for speed. 

We've addressed this by allowing users to ignore certain paths and files from analysis by adding a `.codebeatignore` dotfile to a repo. Feel free to [read more in our docs](https://help.codebeat.co/docs/path-exclusions). Moreover, we'd like to allow users to mark specific functions as "quality checked" by adding comments directly next to their declarations in code. This is a feature we have on the roadmap.

Feel free to try it with `.codebeatignore`

**Comment by liuxuan30** [comment]
@grodowski I have been trying codebeat in my OJ code; generally it's great to see many green light and had a high GPA lol. It's nice to remind myself that trying to write clean code
however, some of the criteria seems not practical in real projects: like the lines of code, the block depth. 
I know you are just starting it up, too many things on the plate, so not sure if you already considered making the criteria flexible to choose which to use. So if some criteria is not a factor for some people, they can turn it off and use other great ones.

**Comment by danielgindi** [comment]
I think it would have been more practical if it was an opt-in configuration instead of opt-out. Then it wouldn't take too much time to configure.

Ideally I would set rules for code styling etc. and it will be checked through git hooks when creating PRs.

**Comment by korzonek** [comment]
@danielgindi this is very good idea. If there are any other improvements you would like to see in codebeat please share it with us. It will helps us prioritise our backlog.Thank you!

**Pull request closed without merging**
