### PR TITLE
Solved XCode7 abort trap:6 bug

### PR DESCRIPTION
**Pull request by eldafito**
Archiving the project in XCode 7 does not throw compiler exception
anymore

### CODE REVIEW

**Comment by liuxuan30** [comment]
Could share why you make the changes this way? What's the difference here.

**Comment by petester42** [comment]
It's a compiler bug. Here is a radar explaining it. http://www.openradar.me/22138918

**Comment by danielgindi** [comment]
Hi!
Thanks for sharing!
There are two problems:
1. The codestyling in your code does not match the code style of the library, and specifically changes existing code to a different, unreadable code style.
2. This is a compiler bug in a *beta* Xcode version, which should be actually fixed by Apple in the next betas...

**Comment by eldafito** [comment]
I can change the codestyling or, if not interested, I'll close the request.

**Comment by danielgindi** [comment]
Let's wait a little for Xcode 7 beta 5 - see if it is fixed. If Apple does not handle that then we'll have to make the workarounds...

**Comment by eldafito** [comment]
ok

**Comment by petester42** [comment]
I actually like this syntax better. It is very clear what the edge conditions are and the variable is only set once so it's easier to follow the assignment.

**Comment by danielgindi** [comment]
We could change the flow to this kind of flow as a refactoring commit....
But it must be clean, not a degradation in quality :-)

**Comment by danielgindi** [comment]
Anyone knows if this was fixed in Xcode 7 beta 5?

**Comment by petester42** [comment]
yes it is. tried the code in the radar on beta-4 and it failed. Beta 5 it compiled fine. :+1:

**Pull request closed without merging**
