### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by eldafito**
Archiving the project in XCode 7 does not throw compiler exception
anymore

### CODE REVIEW

**Comment by petester42** [comment]
Good job! But you created a pull request against master. Could you make a new one but against the swift 2.0 branch. Just to make things easier for everyone.

**Comment by danielgindi** [comment]
There's already a swift-2.0 branch...

‏בתאריך יום שלישי, 4 באוגוסט 2015, Pierre-Marc Airoldi <
notifications@github.com> כתב:

**Comment by petester42** [comment]
Ya I know. That's why the pull request should be made against it and not the master branch. This request is trying to pull in the changes into master.

**Comment by danielgindi** [comment]
It's not time yet... :)
Yeah it needs to be requested against the proper branch

‏בתאריך יום שלישי, 4 באוגוסט 2015, Pierre-Marc Airoldi <
notifications@github.com> כתב:

**Comment by eldafito** [comment]
Sorry for the mistake, now I've requested the pull against the proper branch

**Pull request closed without merging**
