### PR TITLE
Change library name from Charts to DGCharts

### PR DESCRIPTION
**Pull request by pmairoldi**
Apple has introduce their own charts framework for Swift UI with the same name as our library to mitigate the issue that many are having we are renaming our library to DGCharts.

This pull request should address the following issues/prs:
https://github.com/danielgindi/Charts/issues/4845
https://github.com/danielgindi/Charts/issues/4897
https://github.com/danielgindi/Charts/pull/5009

### CODE REVIEW

**Comment by liuxuan30** [comment]
Oh man you saved my day!

**Comment by waterskier2007** [comment]
Awesome! Do we know when to expect the 5.0.0 release?

**Comment by pmairoldi** [comment]
Not sure yet. I’m trying address all the “build” issues but I am having issues with “build for distribution”.

**Comment by liuxuan30** [comment]
> build for distribution

is this caused by the swift-algorithm if I remember correctly?

**Comment by DojoShehab** [comment]
Hey, is there an update on this release?

**Pull request merged**
