### PR TITLE
Correct the spelling of CocoaPods in README

### PR DESCRIPTION
**Pull request by ReadmeCritic**
This pull requests corrects the spelling of **CocoaPods** 🤓
https://github.com/CocoaPods/shared_resources/tree/master/media

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">One day I’ll make a bot that looks through the READMEs of all Pods, looks to see if it uses “Cocoapods” and PRs “CocoaPods” :D</p>&mdash; Ørta (@orta) <a href="https://twitter.com/orta/status/697374357975388160">February 10, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

### CODE REVIEW

**Comment by danielgindi** [comment]
lol :)

**Comment by danielgindi** [comment]
@petester42 do you have an idea why the tests are failing in Travis? They do not fail in Xcode

**Comment by petester42** [comment]
They do fail in Xcode. Maybe you reran the record on your machine so you don't see these errors.

screen shot 2016-02-11 at 20 11 11

**Comment by danielgindi** [comment]
Seems like once in a while tehy do not go in the commit

**Pull request merged**
